/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseterraria;

import javax.swing.JOptionPane;

/**
 * Declaracion de la clase
 * @author MEDAC
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        pnlGeneral = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblintro = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        fldUsuario = new javax.swing.JTextField();
        psfContrasena = new javax.swing.JPasswordField();
        lblInicioSesion = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(239, 229, 255));
        pnlFondo.setLayout(new java.awt.GridBagLayout());

        pnlGeneral.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeneral.setPreferredSize(new java.awt.Dimension(1000, 800));
        pnlGeneral.setLayout(new java.awt.GridBagLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoterraria.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlGeneral.add(lblIcono, gridBagConstraints);

        lblintro.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        lblintro.setForeground(new java.awt.Color(0, 0, 0));
        lblintro.setText("La base de datos de...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 15, 0, 0);
        pnlGeneral.add(lblintro, gridBagConstraints);

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuario.png"))); // NOI18N
        lblUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 20);
        pnlLogin.add(lblUsuario, gridBagConstraints);

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/contrasena.png"))); // NOI18N
        lblContrasena.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        pnlLogin.add(lblContrasena, gridBagConstraints);

        fldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = -7;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlLogin.add(fldUsuario, gridBagConstraints);

        psfContrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlLogin.add(psfContrasena, gridBagConstraints);

        lblInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblInicioSesion.setText("Bienvenido, introduzca las credenciales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlLogin.add(lblInicioSesion, gridBagConstraints);

        btnIniciarSesion.setBackground(new java.awt.Color(153, 255, 153));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(140, 50));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        pnlLogin.add(btnIniciarSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(75, 0, 0, 0);
        pnlGeneral.add(pnlLogin, gridBagConstraints);

        pnlFondo.add(pnlGeneral, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se lanza cuando se pulsa el boton para iniciar sesion, comprueba que ambos campos sean correctos para pasar a la ventana meú
    */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        if(fldUsuario.getText().equals("root")&&psfContrasena.getText().equals("1234")){
           VentanaMenu home = new VentanaMenu();
           home.setVisible(true);
       }
       else if (fldUsuario.getText().equals("")&&psfContrasena.getText().equals("")){
           JOptionPane.showMessageDialog(this, "No has introducido las credenciales, introducelas", "Ausencia de datos",JOptionPane.WARNING_MESSAGE);
       }
       else if (!fldUsuario.getText().equals("root")||!psfContrasena.getText().equals("1234")){
           JOptionPane.showMessageDialog(this, "O la contraseña o el correo son equivocados, vuelve a intentarlo","Error de login",JOptionPane.ERROR_MESSAGE);
           fldUsuario.setText("");
           psfContrasena.setText("");
       }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * El main de VentanaLogin
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JTextField fldUsuario;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblintro;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField psfContrasena;
    // End of variables declaration//GEN-END:variables
}
